In [58]:
import os
import xarray as xr
from glob import glob
import numpy as np
import pandas as pd

#import netcdf4

In [44]:
models = [
          'ACCESS1-0', 'ACCESS1-3', 'CCSM4', 'CESM1-BGC', 'CESM1-CAM5', 'CMCC-CM', 'CMCC-CMS', 'CSIRO-Mk3-6-0', 
          'CanESM2', 'CNRM-CM5', 'EC-EARTH', 'FGOALS-g2', 'GFDL-CM3', 'GFDL-ESM2G', 'GFDL-ESM2M', 'GISS-E2-H',
          'GISS-E2-R', 'HadGEM2-AO', 'HadGEM2-CC', 'HadGEM2-ES', 'IPSL-CM5A-LR', 'IPSL-CM5A-MR', 'MIROC-ESM',
          'MIROC-ESM-CHEM', 'MIROC5', 'MPI-ESM-LR', 'MPI-ESM-MR', 'MRI-CGCM3', 'NorESM1-M', 'bcc-csm1-1',
          'bcc-csm1-1-m', 'inmcm4'
         ]

ext = 'nc'

In [45]:
data_dir = 'data/tasmax'
file_list = glob(os.path.join(data_dir, '*.nc'))
print(file_list)

['data/tasmax/tasmax_CSIRO-Mk3-6-0_2006.nc', 'data/tasmax/tasmax_FGOALS-g2_2007.nc', 'data/tasmax/tasmax_GISS-E2-R_2007.nc', 'data/tasmax/tasmax_ACCESS1-0_2006.nc', 'data/tasmax/tasmax_HadGEM2-AO_2008.nc', 'data/tasmax/tasmax_CMCC-CMS_2007.nc', 'data/tasmax/tasmax_ACCESS1-0_2008.nc', 'data/tasmax/tasmax_CanESM2_2008.nc', 'data/tasmax/tasmax_HadGEM2-CC_2008.nc', 'data/tasmax/tasmax_IPSL-CM5A-MR_2007.nc', 'data/tasmax/tasmax_inmcm4_2006.nc', 'data/tasmax/tasmax_EC-EARTH_2008.nc', 'data/tasmax/tasmax_MPI-ESM-MR_2008.nc', 'data/tasmax/tasmax_GFDL-ESM2G_2007.nc', 'data/tasmax/tasmax_CanESM2_2007.nc', 'data/tasmax/tasmax_CMCC-CM_2006.nc', 'data/tasmax/tasmax_ACCESS1-0_2007.nc', 'data/tasmax/tasmax_MRI-CGCM3_2007.nc', 'data/tasmax/tasmax_MPI-ESM-MR_2007.nc', 'data/tasmax/tasmax_inmcm4_2007.nc', 'data/tasmax/tasmax_MRI-CGCM3_2006.nc', 'data/tasmax/tasmax_CCSM4_2007.nc', 'data/tasmax/tasmax_MRI-CGCM3_2008.nc', 'data/tasmax/tasmax_MPI-ESM-LR_2008.nc', 'data/tasmax/tasmax_CMCC-CM_2008.nc', 'data/tasmax/tasmax_CCSM4_2006.nc', 'data/tasmax/tasmax_FGOALS-g2_2008.nc', 'data/tasmax/tasmax_MIROC5_2006.nc', 'data/tasmax/tasmax_bcc-csm1-1_2007.nc', 'data/tasmax/tasmax_ACCESS1-3_2007.nc', 'data/tasmax/tasmax_GFDL-ESM2G_2008.nc', 'data/tasmax/tasmax_GISS-E2-R_2008.nc', 'data/tasmax/tasmax_ACCESS1-3_2008.nc', 'data/tasmax/tasmax_MIROC-ESM_2008.nc', 'data/tasmax/tasmax_CESM1-BGC_2007.nc', 'data/tasmax/tasmax_HadGEM2-ES_2008.nc', 'data/tasmax/tasmax_HadGEM2-CC_2006.nc', 'data/tasmax/tasmax_CMCC-CMS_2008.nc', 'data/tasmax/tasmax_CESM1-BGC_2006.nc', 'data/tasmax/tasmax_GFDL-ESM2M_2008.nc', 'data/tasmax/tasmax_CESM1-CAM5_2006.nc', 'data/tasmax/tasmax_inmcm4_2008.nc', 'data/tasmax/tasmax_CCSM4_2008.nc', 'data/tasmax/tasmax_CMCC-CMS_2006.nc', 'data/tasmax/tasmax_MIROC5_2008.nc', 'data/tasmax/tasmax_MIROC-ESM-CHEM_2006.nc', 'data/tasmax/tasmax_GFDL-CM3_2006.nc', 'data/tasmax/tasmax_bcc-csm1-1-m_2006.nc', 'data/tasmax/tasmax_FGOALS-g2_2006.nc', 'data/tasmax/tasmax_CNRM-CM5_2007.nc', 'data/tasmax/tasmax_GISS-E2-R_2006.nc', 'data/tasmax/tasmax_MIROC5_2007.nc', 'data/tasmax/tasmax_EC-EARTH_2006.nc', 'data/tasmax/tasmax_GISS-E2-H_2007.nc', 'data/tasmax/tasmax_GFDL-ESM2G_2006.nc', 'data/tasmax/tasmax_GFDL-CM3_2007.nc', 'data/tasmax/tasmax_MIROC-ESM_2007.nc', 'data/tasmax/tasmax_MIROC-ESM-CHEM_2007.nc', 'data/tasmax/tasmax_CMCC-CM_2007.nc', 'data/tasmax/tasmax_CESM1-BGC_2008.nc', 'data/tasmax/tasmax_CESM1-CAM5_2007.nc', 'data/tasmax/tasmax_HadGEM2-AO_2006.nc', 'data/tasmax/tasmax_EC-EARTH_2007.nc', 'data/tasmax/tasmax_CSIRO-Mk3-6-0_2007.nc', 'data/tasmax/tasmax_HadGEM2-ES_2006.nc', 'data/tasmax/tasmax_bcc-csm1-1-m_2007.nc', 'data/tasmax/tasmax_HadGEM2-ES_2007.nc', 'data/tasmax/tasmax_bcc-csm1-1-m_2008.nc', 'data/tasmax/tasmax_HadGEM2-AO_2007.nc', 'data/tasmax/tasmax_NorESM1-M_2006.nc', 'data/tasmax/tasmax_GFDL-ESM2M_2006.nc', 'data/tasmax/tasmax_MIROC-ESM_2006.nc', 'data/tasmax/tasmax_IPSL-CM5A-LR_2008.nc', 'data/tasmax/tasmax_GFDL-ESM2M_2007.nc', 'data/tasmax/tasmax_CESM1-CAM5_2008.nc', 'data/tasmax/tasmax_MIROC-ESM-CHEM_2008.nc', 'data/tasmax/tasmax_ACCESS1-3_2006.nc', 'data/tasmax/tasmax_MPI-ESM-MR_2006.nc', 'data/tasmax/tasmax_IPSL-CM5A-LR_2007.nc', 'data/tasmax/tasmax_MPI-ESM-LR_2006.nc', 'data/tasmax/tasmax_CNRM-CM5_2008.nc', 'data/tasmax/tasmax_CSIRO-Mk3-6-0_2008.nc', 'data/tasmax/tasmax_IPSL-CM5A-MR_2006.nc', 'data/tasmax/tasmax_NorESM1-M_2007.nc', 'data/tasmax/tasmax_HadGEM2-CC_2007.nc', 'data/tasmax/tasmax_IPSL-CM5A-MR_2008.nc', 'data/tasmax/tasmax_bcc-csm1-1_2006.nc', 'data/tasmax/tasmax_CanESM2_2006.nc', 'data/tasmax/tasmax_CNRM-CM5_2006.nc', 'data/tasmax/tasmax_MPI-ESM-LR_2007.nc', 'data/tasmax/tasmax_IPSL-CM5A-LR_2006.nc', 'data/tasmax/tasmax_GFDL-CM3_2008.nc', 'data/tasmax/tasmax_GISS-E2-H_2008.nc', 'data/tasmax/tasmax_GISS-E2-H_2006.nc', 'data/tasmax/tasmax_NorESM1-M_2008.nc', 'data/tasmax/tasmax_bcc-csm1-1_2008.nc']

In [47]:
def calc_daily_avg():
    df_list = []
    #for file in file_list[:2]:
    for file in file_list:
        ds = xr.open_dataset(file)
        tasmax = ds['tasmax']
        data = tasmax.sel(lat=38.59375, lon=(360-121.46875), method='nearest')
        df = pd.DataFrame(data.to_pandas())
        model = file.split('_')[1]
        df['model'] = model
        df['year'] = model
        ds.close()
        df_list.append(df) 
    return pd.concat(df_list)

In [48]:
daily_df = calc_daily_avg()

In [49]:
daily_df['year'] = daily_df.index.year
daily_df['month'] = daily_df.index.month
daily_df['wateryear'] = np.where(daily_df['month'] > 9, daily_df['year'] + 1, daily_df['year'])
daily_df

                              0          model  year  month  wateryear
time
2006-01-01 12:00:00  285.333008  CSIRO-Mk3-6-0  2006      1       2006
2006-01-02 12:00:00  279.371338  CSIRO-Mk3-6-0  2006      1       2006
2006-01-03 12:00:00  281.004456  CSIRO-Mk3-6-0  2006      1       2006
2006-01-04 12:00:00  281.116974  CSIRO-Mk3-6-0  2006      1       2006
2006-01-05 12:00:00  280.612762  CSIRO-Mk3-6-0  2006      1       2006
2006-01-06 12:00:00  279.423981  CSIRO-Mk3-6-0  2006      1       2006
2006-01-07 12:00:00  277.866180  CSIRO-Mk3-6-0  2006      1       2006
2006-01-08 12:00:00  284.577942  CSIRO-Mk3-6-0  2006      1       2006
2006-01-09 12:00:00  283.748352  CSIRO-Mk3-6-0  2006      1       2006
2006-01-10 12:00:00  282.931976  CSIRO-Mk3-6-0  2006      1       2006
2006-01-11 12:00:00  287.413849  CSIRO-Mk3-6-0  2006      1       2006
2006-01-12 12:00:00  286.080841  CSIRO-Mk3-6-0  2006      1       2006
2006-01-13 12:00:00  282.024994  CSIRO-Mk3-6-0  2006      1       2006
2006-01-14 12:00:00  280.235077  CSIRO-Mk3-6-0  2006      1       2006
2006-01-15 12:00:00  281.171844  CSIRO-Mk3-6-0  2006      1       2006
2006-01-16 12:00:00  281.553162  CSIRO-Mk3-6-0  2006      1       2006
2006-01-17 12:00:00  281.512482  CSIRO-Mk3-6-0  2006      1       2006
2006-01-18 12:00:00  279.924652  CSIRO-Mk3-6-0  2006      1       2006
2006-01-19 12:00:00  285.147339  CSIRO-Mk3-6-0  2006      1       2006
2006-01-20 12:00:00  285.297821  CSIRO-Mk3-6-0  2006      1       2006
2006-01-21 12:00:00  286.381744  CSIRO-Mk3-6-0  2006      1       2006
2006-01-22 12:00:00  284.290710  CSIRO-Mk3-6-0  2006      1       2006
2006-01-23 12:00:00  284.682129  CSIRO-Mk3-6-0  2006      1       2006
2006-01-24 12:00:00  288.155273  CSIRO-Mk3-6-0  2006      1       2006
2006-01-25 12:00:00  284.734497  CSIRO-Mk3-6-0  2006      1       2006
2006-01-26 12:00:00  290.490326  CSIRO-Mk3-6-0  2006      1       2006
2006-01-27 12:00:00  288.890717  CSIRO-Mk3-6-0  2006      1       2006
2006-01-28 12:00:00  291.220154  CSIRO-Mk3-6-0  2006      1       2006
2006-01-29 12:00:00  290.493195  CSIRO-Mk3-6-0  2006      1       2006
2006-01-30 12:00:00  288.377594  CSIRO-Mk3-6-0  2006      1       2006
...                         ...            ...   ...    ...        ...
2008-12-02 12:00:00  280.772949     bcc-csm1-1  2008     12       2009
2008-12-03 12:00:00  287.918915     bcc-csm1-1  2008     12       2009
2008-12-04 12:00:00  287.816498     bcc-csm1-1  2008     12       2009
2008-12-05 12:00:00  290.385742     bcc-csm1-1  2008     12       2009
2008-12-06 12:00:00  290.124908     bcc-csm1-1  2008     12       2009
2008-12-07 12:00:00  287.864899     bcc-csm1-1  2008     12       2009
2008-12-08 12:00:00  287.679810     bcc-csm1-1  2008     12       2009
2008-12-09 12:00:00  286.087860     bcc-csm1-1  2008     12       2009
2008-12-10 12:00:00  287.014771     bcc-csm1-1  2008     12       2009
2008-12-11 12:00:00  287.124542     bcc-csm1-1  2008     12       2009
2008-12-12 12:00:00  286.154907     bcc-csm1-1  2008     12       2009
2008-12-13 12:00:00  282.411469     bcc-csm1-1  2008     12       2009
2008-12-14 12:00:00  283.958435     bcc-csm1-1  2008     12       2009
2008-12-15 12:00:00  284.837616     bcc-csm1-1  2008     12       2009
2008-12-16 12:00:00  285.360168     bcc-csm1-1  2008     12       2009
2008-12-17 12:00:00  286.410675     bcc-csm1-1  2008     12       2009
2008-12-18 12:00:00  286.129669     bcc-csm1-1  2008     12       2009
2008-12-19 12:00:00  285.055450     bcc-csm1-1  2008     12       2009
2008-12-20 12:00:00  284.895142     bcc-csm1-1  2008     12       2009
2008-12-21 12:00:00  284.036102     bcc-csm1-1  2008     12       2009
2008-12-22 12:00:00  282.992004     bcc-csm1-1  2008     12       2009
2008-12-23 12:00:00  286.102295     bcc-csm1-1  2008     12       2009
2008-12-24 12:00:00  283.160309     bcc-csm1-1  2008     12       2009
2008-12-25 12:00:00  283.548065     bcc-csm1-1  2008     12       2009
2008-12-26 12:00:00  283.910370     bcc-csm1-1  2008     12       2009
2008-12-27 12:00:00  285.315521     bcc-csm1-1  2008     12       2009
2008-12-28 12:00:00  285.252716     bcc-csm1-1  2008     12       2009
2008-12-29 12:00:00  283.090668     bcc-csm1-1  2008     12       2009
2008-12-30 12:00:00  279.461365     bcc-csm1-1  2008     12       2009
2008-12-31 12:00:00  281.295746     bcc-csm1-1  2008     12       2009

[35072 rows x 5 columns]

In [50]:
calendar_year = daily_df.groupby(['model', 'year'])[0].mean()
calendar_year

model           year
ACCESS1-0       2006    298.407898
                2007    298.003754
                2008    298.575348
ACCESS1-3       2006    297.063568
                2007    297.719910
                2008    297.048340
CCSM4           2006    297.452179
                2007    297.840363
                2008    298.055573
CESM1-BGC       2006    297.817749
                2007    297.679718
                2008    298.143799
CESM1-CAM5      2006    297.290619
                2007    297.972290
                2008    297.147278
CMCC-CM         2006    296.831451
                2007    296.548523
                2008    295.602234
CMCC-CMS        2006    297.202698
                2007    298.586212
                2008    298.263580
CNRM-CM5        2006    297.332214
                2007    298.116241
                2008    298.264252
CSIRO-Mk3-6-0   2006    297.712738
                2007    298.335052
                2008    297.697662
CanESM2         2006    297.114868
                2007    298.245941
                2008    297.138794
                           ...
MIROC-ESM       2006    298.917114
                2007    297.428864
                2008    295.877014
MIROC-ESM-CHEM  2006    296.944489
                2007    297.069672
                2008    297.018860
MIROC5          2006    297.691925
                2007    297.869995
                2008    297.377014
MPI-ESM-LR      2006    297.833282
                2007    298.052551
                2008    296.120178
MPI-ESM-MR      2006    297.508972
                2007    297.215240
                2008    296.708710
MRI-CGCM3       2006    297.916931
                2007    295.870850
                2008    296.885193
NorESM1-M       2006    297.667419
                2007    296.816528
                2008    298.250977
bcc-csm1-1      2006    298.247620
                2007    297.166687
                2008    296.941376
bcc-csm1-1-m    2006    296.996368
                2007    296.871521
                2008    297.498260
inmcm4          2006    296.626892
                2007    296.453400
                2008    296.731293
Name: 0, Length: 96, dtype: float32

In [57]:
print('Calendar year min from daily data')
print(calendar_year.groupby('year').min())
print('Calendar year max from daily data')
print(calendar_year.groupby('year').max())

Calendar year min from daily data
year
2006    296.052460
2007    295.870850
2008    295.602234
Name: 0, dtype: float32
Calendar year max from daily data
year
2006    299.512024
2007    298.839325
2008    298.575348
Name: 0, dtype: float32

In [52]:
water_year = daily_df.groupby(['model', 'wateryear'])[0].mean()
water_year

model         wateryear
ACCESS1-0     2006         300.371246
              2007         298.006683
              2008         298.586212
              2009         292.526978
ACCESS1-3     2006         298.211853
              2007         298.009979
              2008         297.197693
              2009         291.911224
CCSM4         2006         299.268341
              2007         297.519501
              2008         298.413727
              2009         291.911102
CESM1-BGC     2006         300.110291
              2007         296.953766
              2008         298.442902
              2009         292.705109
CESM1-CAM5    2006         298.988007
              2007         297.849518
              2008         297.154510
              2009         292.712067
CMCC-CM       2006         298.371368
              2007         295.917328
              2008         296.310883
              2009         291.946930
CMCC-CMS      2006         298.790466
              2007         298.830414
              2008         297.894379
              2009         292.991089
CNRM-CM5      2006         299.182495
              2007         297.623138
                              ...
MIROC5        2008         297.216309
              2009         292.481110
MPI-ESM-LR    2006         298.924713
              2007         298.672302
              2008         296.434113
              2009         290.886932
MPI-ESM-MR    2006         298.911499
              2007         297.942169
              2008         296.006500
              2009         293.256683
MRI-CGCM3     2006         299.433197
              2007         296.360291
              2008         296.910706
              2009         291.374298
NorESM1-M     2006         299.424957
              2007         297.027313
              2008         298.264862
              2009         291.560516
bcc-csm1-1    2006         299.926514
              2007         297.363098
              2008         297.062897
              2009         292.003052
bcc-csm1-1-m  2006         298.876068
              2007         297.063782
              2008         297.186096
              2009         291.897736
inmcm4        2006         298.450409
              2007         296.153137
              2008         296.987793
              2009         291.386536
Name: 0, Length: 128, dtype: float32

In [56]:
print('NOTE: Ignore values for first and last year in the list below')
print('Water year min from daily data')
print(water_year.groupby('wateryear').min())
print('Water year max from daily data')
print(water_year.groupby('wateryear').max())

NOTE: Ignore values for first and last year in the list below
Water year min from daily data
wateryear
2006    297.839142
2007    295.917328
2008    295.770325
2009    289.920990
Name: 0, dtype: float32
Water year max from daily data
wateryear
2006    301.511963
2007    299.092346
2008    298.877563
2009    294.120300
Name: 0, dtype: float32